# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# uv_nc_to_s_tif.py
# Created on: 2014-10-03 11:46:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Load required toolboxes
arcpy.ImportToolbox("H:/esm296-4f/lab1/lab1.tbx")


# Local variables:
uwnd_sig995_2013_nc = "H:\\esm296-4f\\lab1\\raw\\uwnd.sig995.2013.nc"
vwnd_sig995_2013_nc = "H:\\esm296-4f\\lab1\\raw\\vwnd.sig995.2013.nc"
u_001 = "u_001"
v_001 = "v_001"
s_001 = "in_memory\\s_001"
s_001_tif = "H:\\esm296-4f\\lab1\\out\\s_001.tif"

# Process: Make NetCDF Raster Layer
arcpy.MakeNetCDFRasterLayer_md(uwnd_sig995_2013_nc, "uwnd", "lon", "lat", u_001, "", "time 1", "BY_INDEX")

# Process: Make NetCDF Raster Layer (2)
arcpy.MakeNetCDFRasterLayer_md(vwnd_sig995_2013_nc, "vwnd", "lon", "lat", v_001, "", "time 1", "BY_INDEX")

# Process: Raster Calculator
arcpy.gp.toolbox = "H:/esm296-4f/lab1/lab1.tbx";
# Warning: the toolbox H:/esm296-4f/lab1/lab1.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.RasterCalculator(...) with arcpy.RasterCalculator_ALIAS(...)
arcpy.gp.RasterCalculator("SquareRoot(Square(\"%u_001%\") + Square(\"%v_001%\"))", s_001)

# Process: Resample
arcpy.gp.toolbox = "H:/esm296-4f/lab1/lab1.tbx";
# Warning: the toolbox H:/esm296-4f/lab1/lab1.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.Resample(...) with arcpy.Resample_ALIAS(...)
arcpy.gp.Resample(s_001, s_001_tif, "0.25 0.25", "BILINEAR")

